version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mf_db
    environment:
      POSTGRES_USER: mfuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mfdb
    ports:
      - "5432:5432"
    volumes:
      - mf_data:/var/lib/postgresql/data

volumes:
  mf_data:
